name: Daily Report Push

on:
  schedule:
    - cron: "7 1 * * *"
    - cron: "7 4 * * *"
    - cron: "7 10 * * *"
  workflow_dispatch:

jobs:
  send:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Send daily report
        env:
          SCT_SENDKEY: ${{ secrets.SCT_SENDKEY }}
          MSG_CITY: "Guangzhou"
        run: python 每日问候/send_daily_msg.py
